### PR TITLE
Skip the root validators

### PR DESCRIPTION
**Pull request by regebro**
The schema now added another type of validator, and rather than keeping multiple types of arbitrary validators up to date we currently skip them.

If we want this type of validation we probably need to implement something generic that supports more JSON schema requriements.

### CODE REVIEW

**Comment by kedder** [comment]
Very difficult to spot the actual changes in the diff

**Comment by regebro** [comment]
@kedder  Yes, somehow the black formatting wasn't applied when I pushed, not sure how that happened. Fixed now.

**Review by kedder — APPROVED** [review]

**Comment by kedder** [comment]
you can reformat in a separate commit

**Comment by regebro** [comment]
There should not have been a reformat at all, I didn't notice that there
was.

**Pull request merged**
